gText_Birch_Welcome::
	.string "One year ago, a meteorite containing\n"
	.string "an alien virus landed in Hoen.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "The virus mutated into a\n"
	.string "host creature we call 'Deoxys.'$"

gText_Birch_MainSpeech::
	.string "The world we once knew has been\n" 
	.string "utterly devasted.\p"
	.string "Deoxys has sent out drones capable\n"
	.string "capable of mimicking any\p"
	.string "form of life throughout Hoen.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "I need to verify your identity.\p"
	.string "$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\p"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Trust no one.\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "Exterminate the drones and Deoxys.\n"
	.string "You are our last hope.\p"
	.string "$"
